{
 "title": "Provider Performance Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "provider",
    "query": {
     "query": "label_values(oracle_api_response_status_per_provider,provider)"
    }
   },
   {
    "name": "pair",
    "label": "Currency Pair",
    "query": {
     "query": "label_values(oracle_aggregate_price,pair)"
    }
   },
   {
    "name": "id",
    "query": {
     "query": "label_values(oracle_api_response_status_per_provider,id)"
    }
   },
   {
    "name": "decimals",
    "query": {
     "query": "label_values(oracle_provider_price,decimals)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(oracle_provider_status_responses,status)"
    }
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(oracle_provider_status_responses,code)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(oracle_provider_status_responses,type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Provider API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Provider Responses by Status Per Hour",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (increase(oracle_api_response_status_per_provider{provider=\"$provider\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Number of Provider Responses by ID Per Hour",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 13, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id, status) (increase(oracle_api_response_status_per_provider{provider=\"$provider\", id=\"$id\"}[1h]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Base Provider Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Number of Responses per Provider and Status per Hour",
     "type": "stat",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (provider, status) (increase(oracle_provider_status_responses{provider=~\"$provider\", status=~\"$status\"}[1h])) / (60 * 60)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Number of Responses per ID per Hour",
     "type": "stat",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (id, status) (increase(oracle_provider_status_responses_per_id{provider=~\"$provider\", status=~\"$status\", id=~\"$id\"}[1h])) / (60 * 60)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Prices & Charts ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Oracle Aggregate Price Chart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "oracle_aggregate_price{pair=~\"$pair\"} / 10 ^ $decimals",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Provider Price Chart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracle_provider_price{pair=~\"$pair\", type=~\"$type\", provider=~\"$provider\"} / 10 ^ $decimals",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Aggregate Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_aggregate_price{pair=~\"$pair\"} / 10 ^ $decimals",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Provider Price",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_provider_price{pair=~\"$pair\", type=~\"$type\", provider=~\"$provider\"} / 10 ^ $decimals",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle Provider Last Updated Time For Each Currency Pair in Seconds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - oracle_provider_last_updated_id{id=\"$id\", provider=\"$provider\", type=\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Oracle Ticks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(oracle_ticks_total[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}